project:
  type: website
  render:
    - "*.qmd"
    - "!*.md"
    - "!*.ipynb"
website:
  title: "Scott Powers"
  favicon: assets/favicon_dark.png
  search: false
  navbar:
    right:
      - research/index.qmd
      - software/index.qmd
      - teaching/index.qmd
      - lab/index.qmd
      - jobs/index.qmd
      - text: CV
        href: assets/powers.pdf
        target: _blank
format:
  html:
    theme:
      - solar
      - custom.scss
    css: styles.css
    toc: true
    page-layout: full
