---
title: "Advice on becoming a competitive candidate for jobs in sport analytics"
toc: false
---

When I was a hiring manager in analytics for the Dodgers, we would post an entry-level quantitative analyst position and receive nearly a thousand applications. Among those candidates, based on the application alone, roughly half would seem to be qualified for the entry-level position. Without the resources to interview 500 candidates, we had to decide which small subset of candidates would advance to the interview stage (this is its own challenge and a story for another day).

I relay this experience to you because it conveys some perspective from the other side of the job application process. How will you separate yourself (before the interview stage) from the many other candidates who could be qualified for the position? The best way to make your resume rise to the top of the stack is to **work on a research project and present it at a sport analytics conference.** If a resume reviewer is already familiar with your work (assuming it's good work) before seeing your name in the candidate pool, then they are much more likely to offer you an interview. Below, I've listed some opportunities to stand out.

**General Sports.** [New England Symposium on Statistics in Sports](https://nessis.org/){target=_blank} (September, Boston) and [Cascadia Symposium on Statistics in Sports](http://cascadiasports.com/){target=_blank} (September, Vancouver) are sibling conferences, with NESSIS occurring in odd-numbered years and CASSIS occurring in even-numbered years. The academic quality of presentations at these conferences is generally very high. It can be difficult for students to earn presentation slots on stage, but there are also opportunities to give poster presentations. For women and candidates of non-binary gender, [Women in Sports Data Symposium](https://www.womeninsportsdata.org/){target=_blank} (September, Philadelphia) can be an excellent opportunity to present your work on stage in front of industry professionals, including hiring managers. The WISD Symposium features a strong industry presence of any gender in the audience.

**Baseball.** [Saberseminar](https://www.saberseminar.com/){target=_blank} (August, Chicago) is a very accessible entry point for students seeking to give their first on-stage presentation at a major conference, featuring 10-minute student presentation slots. Most MLB clubs sponsor and send representatives to Saberseminar. [SABR Analytics Conference](https://sabr.org/analytics){target=_blank} (March, Phoenix) is a bit more competitive to get a presentation slot, and it is also well-sponsored and well-attended by MLB clubs.

**Football.** It's not a conference, but the NFL's [Big Data Bowl](https://operations.nfl.com/gameday/analytics/big-data-bowl/){target=_blank} is *the* hiring pipeline for football analytics. The contest typically runs from October into January and features thousands(!) of entrants. For this contest, the NFL makes available tracking(!) data and as much as $100,000(!) in prize money. The top contestants are invited to present their work at the NFL Combine (Indianapolis, February) in front of a star-student judge panel that may include a current NFL player(!).

**Soccer.** For those of you in Europe (sorry for calling it soccer), [Statsbomb Conference](https://statsbomb.com/events/){target=_blank} (Manchester, October) and [Opta Forum](https://www.statsperform.com/resource/pro-forum-presenters-where-are-they-now/){target=_blank} (London, March) both allow students (and non-students) to submit research proposals. The top proposals receive proprietary data to complete their projects and invitations to present their work on stage at the events. For those of you in North America, the nascent [American Soccer Insights Summit](https://americansoccerinsights.com/){target=_blank} (Houston, January) follows a similar format, with a call for proposals, proprietary data and an opportunity to present on stage.
